# Generated by Django 3.1.7 on 2021-04-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='facebook',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='instragram',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='twitter',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
