# Generated by Django 3.1.7 on 2021-04-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_auto_20210401_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='facebook',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='instragram',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='twitter',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
